/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hazelcast_query_misonparser_SIMDHelper */

#ifndef _Included_com_hazelcast_query_misonparser_SIMDHelper
#define _Included_com_hazelcast_query_misonparser_SIMDHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hazelcast_query_misonparser_SIMDHelper
 * Method:    createCharacterIndexes
 * Signature: (Ljava/lang/String;ILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_hazelcast_query_misonparser_SIMDHelper_createCharacterIndexes
  (JNIEnv *, jclass, jstring, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
